# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language

  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

ko:
  languageCode: ko
  contentDir: content/ko  # 한국어 콘텐츠 폴더
  title: '유빈의 개발 프로필'  # 한국어 제목
  params:
    description: '전북대학교 문유빈의 개발자 프로필 입니다.'  # 한국어 설명
  menu:
    main:
      - name: 메인
        url: /#top
        weight: 10
      - name: 정보
        url: /#info
        weight: 20
      - name: 기술 스택
        url: /#skills
        weight: 30
      - name: 프로젝트
        url: /#graduation-project
        weight: 40
      - name: 이력서
        url: /#resume
        weight: 50
        hasChildren: true
      - parent: 스터디
        name: 스터디 블로그
        url: blog/



# English language configuration
en:
  languageCode: en-us
  contentDir: content/en  # 영어 콘텐츠 폴더
  title: 'Yubin Developer Profile'  # 영어 제목
  params:
    description: 'This is JBNU MOON YUBIN Developer Profile'  # 영어 설명
  menu:
    main:
      - name: Home
        url: /#top
        weight: 10
      - name: Info
        url: /#info
        weight: 20
      - name: Skills
        url: /#skills
        weight: 30
      - name: Project
        url: /#graduation-project
        weight: 40
      - name: Resume
        url: /#resume
        weight: 50
        hasChildren: true
      - parent: Study
        name: Blog
        url: blog/



















# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
